version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: auction-root-password
      MYSQL_DATABASE: auction-db
      MYSQL_USER: auction-user
      MYSQL_PASSWORD: auction-password
    ports:
      - "3306:3306"
    volumes:
      - ~/docker-volumes/mysql-data:/var/lib/mysql