spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 콘솔 활성화 (http://localhost:8080/h2-console)
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j

---
spring:
  config:
    activate:
      on-profile:
        - dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auction-db
    username: auction-user
    password: auction-password

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j