server:
  port: 8080
  shutdown: graceful

springdoc:
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

spring:
  application:
    name: auction-api
  profiles:
    active: test
    include:
      - persistence
  jackson:
    default-property-inclusion: non_null

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: dev
---